#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Docopt\Handler;

$doc = <<<DOC
gendiff cli tool

Usage:
  cli.php [options] <file> [--output=<output>]
  cli.php -h | --help

Options:
  -h --help            Show this screen.
  --output=<output>    Output file [default: out.txt].
DOC;

$handler = new Handler();
$args = $handler->handle($doc);

// Вывод справки, если передан -h или --help
if ($args['--help'] || $args['-h']) {
    echo $doc;
    exit(0);
}