#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use Docopt\Handler;

$doc = <<<DOC
gendiff cli tool Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format=<fmt>] <firstFile> <secondFile> [--output=<output>]

Options:
  -h --help             Show this screen.
  -v --version          Show version.
  --format=<fmt>        Output format (plain, json, stylish) [default: stylish].
DOC;

$handler = new Handler();
$args = $handler->handle($doc);

// Вывод справки, если передан -h или --help
if ($args['--help'] || $args['-h']) {
    echo $doc;
    exit(0);
}

// Вывод версии
if ($args['--version'] || $args['-v']) {
    echo "Gendiff Version: 0.1 \n";
    exit(0);
}

// Основная логика
if (isset($args['<firstFile>']) && isset($args['<secondFile>'])) {
    echo "Comparing files: {$args['<firstFile>']} and {$args['<secondFile>']}\n";
    echo "Format: {$args['--format']}\n";
    echo "Output: {$args['--output']}\n";
} else {
    echo "Error: You must specify two files.\n";
    exit(1);
}